name: sleep
on:
  pull_request:
    branches: [ main ]

jobs:
  sleep-1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 30
  sleep-2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 60
  sleep-3:
    runs-on: ubuntu-latest
    needs: sleep-1
    steps:
      - name: Sleep
        run: sleep 30
